[profile.default]
src = "src"
out = "out"
libs = ["lib"]
extra_output_files = ["abi"]

[profile.deploy]
solc = "0.8.23"
optimizer = true
optimizer_runs = 999999

[fmt]
sort_imports = true
wrap_comments = true
